= System setup

In this lab, you will be cloning the lab helper scripts and preparing
the host, as well as setting up the required access for Red Hat resources.

[#repo]
== Installing Repositories

First, let's start by cloning the helper scripts.

[source,bash]
----
git clone https://github.com/kwozyman/rh-summit-2024-lb1506
----

...and changing our directory to the newly created one:

[source,bash]
----
cd rh-summit-2024-lb1506
----

[#login]
== Red Hat registry login

In order to use the base Red Hat container images, you need to login to Red Hat's image container registry
by using your Red Hat account credentials. If you do not have a service account, visit
https://access.redhat.com/terms-based-registry and click “New service account”. From there click the name
of the new entry and copy/paste the “docker login” instructions in the terminal, replacing the docker
command with podman. Full instructions are https://access.redhat.com/RegistryAuthentication[here] if more
information is needed.

[source,bash]
----
podman login registry.redhat.io
----

You will be asked for a username (this is typically the email address associated with your account) and
a password.

NOTE: If you cannot login to the Red Hat registry but you still want to continue this lab, you can use the
command `git checkout centos` to switch to using the publicly available CentOS Stream9 container images. You will also
have to replace any occurences of `registry.redhat.io/rhel9/rhel-bootc:9.4` with `quay.io/centos-bootc/centos-bootc`
wherever they appear in this document.

[#high-level]
== Preparing the host for container building

In this final part of the setup, you will:

  * setup the hypervisor for running virtual machines
  * generate a local ssh key
  * run a local container image registry
  * download all the required container images

Don't worry if this sounds like a lot, there is a script to do it all for you:

[source,bash]
----
make setup
----

[#status]
== Checking the setup

One final check before you advance to the next lab.

[source,bash]
----
make status
----

The output from the command above should be similar to the following:

----
git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
podman login --get-login registry.redhat.io
cgament@redhat.com
podman image exists "registry.redhat.io/rhel9/rhel-bootc:9.4"
podman image exists "quay.io/centos-bootc/bootc-image-builder:latest"
podman image exists registry.access.redhat.com/ubi9/ubi-minimal
podman image exists registry.access.redhat.com/ubi9/ubi
podman image exists quay.io/kwozyman/toolbox:httpd
podman image exists quay.io/kwozyman/toolbox:registry
     Active: active (running) since Wed 2024-05-01 17:13:37 EDT; 55s ago
 Id   Name   State
--------------------

net.ipv4.ip_unprivileged_port_start = 80
ID            NAME             CPU %       MEM USAGE / LIMIT  MEM %       NET IO            BLOCK IO    PIDS        CPU TIME    AVG CPU %
fa77d569b19f  summit-registry  0.05%       17.9MB / 67.3GB    0.03%       3.88kB / 1.888kB  0B / 0B     20          18.923277s  0.05%
----
