= Deploy a bootc virtual machine with prebuilt image

In this lab, you will build a `qcow2` libvirt image out of the bootc container and then boot
a virtual machine using it.

`qcow2` is a standard file format used by the Linux virtualization system.

[#config]
== Create the config for building the virtual machine image

You may have noticed the bootc container image we've created does not include any login credentials.
In order to be able to login to the future virtual machine, you need to create a JSON file with the credentials.

A ssh key has been generated in the Setup section of this lab. You can view the public part like this:

[source,bash]
----
cat ~/.ssh/id_rsa.pub
----

The output should look something like this (Example):

----
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAuXnpoluye+KM+9tvIAdHf+F0IHh+K73tlcjEG8LJRB lab-user@hypervisor
----

You can now create a file called `config-qcow2.json` with the following contents, replacing the `key` field with the ssh key from your system:

[source,json]
----
{
  "blueprint": {
    "customizations": {
      "user": [
        {
          "name": "lab-user",
          "password": "lb1506",
          "key": "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAuXnpoluye+KM+9tvIAdHf+F0IHh+K73tlcjEG8LJRB lab-user@hypervisor",
          "groups": [
            "wheel"
          ]
        }
      ]
    }
  }
}
----

The above file creates a user `lab-user` with the password `lb1506` and the ssh key in the generated virtual machine image.

NOTE: For your convenience, a config file has already been generated with the ssh key for your lab host in `config/config-qcow2.json` so
you can just use that with `cp config/config-qcow2.json config-qcow2.json`.

[#create]
== Create the virtual machine image

In this section, we will assume you are using the bootc image generated in the previous part of the lab tagged `summit.registry/lb1506:bootc`.

First, you want to make sure the bootc image is pushed to the local registry:

[source,bash]
----
podman push summit.registry/lb1506:bootc
----

In order to build the qcow image, you will use a containerized tool called `bootc-image-builder`. For image builder to work,
it needs `root` permissions. Try to generate the image now:

[source,bash]
----
sudo podman run --rm --privileged \
        --volume .:/output \
        --volume ./config-qcow2.json:/config.json \
        registry.redhat.io/rhel9/bootc-image-builder:latest \
        --type qcow2 --config /config.json \
        --tls-verify=false \
        summit.registry/lb1506:bootc
----

A brief explanation of the arguments used:

  * `--rm` -> do not keep the build container after execution finishes
  * `--privileged` -> root permissions are required to build the image
  * `--volume` -> podman will map these local directories or files to the container
  * `registry.redhat.io/rhel9/bootc-image-builder:latest` -> the image builder container image
  * `--type qcow2` -> the type of image to build
  * `--config /config.json` -> the json configuration file used; please note this is relative to the container filesystem
  * `--tls-verify=false` -> the registry we are running is local and it has self signed certificates; this flag would not be needed with `quay.io` for example
  * `summit.registry/lb1506:bootc` -> the image we are trying to pack into qcow2

If the previous command was successful, you should be able to see the image is the `qcow2/` directory:

[source,bash]
----
ls -lah qcow2/disk.qcow2
----

The output should be similar to:

[source]
----
-rw-r--r--. 1 root root 945M May  2 06:10 qcow2/disk.qcow2
----

NOTE: for your convenience, this part of the exercise is automated by using the `make qcow CONTAINER=summit.registry/lb1506:bootc` command

NOTE: if you are using CentOS Stream 9, the `registry.redhat.io/rhel9/bootc-image-builder:latest` can be replaced with `quay.io/centos-bootc/bootc-image-builder:latest`

[#create-vm]
== Create the virtual machine

Creating and running a virtual machine is out of scope for this lab, so this step has been automated
in the Makefile:

[source,bash]
----
make vm-qcow
----

For reference, the manual command is (you do not need to run this command):

[source,bash]
----
sudo cp qcow2/disk.qcow2 /var/lib/libvirt/images/summit/qcow-vm.qcow2
virt-install --connect qemu:///system \
        --name qcow-vm \
        --disk /var/lib/libvirt/images/summit/qcow-vm.qcow2 \
        --network "network=summit-network,mac=de:ad:be:ef:01:03" \
        --memory 4096 --graphics none --noreboot
virsh --connect qemu:///system start qcow-vm
----

If `make vm-qcow` was successful, you should see the virtual machine running:

[source,bash]
----
virsh --connect qemu:///system list

 Id   Name                State
------------------------------------
 5    qcow-vm             running
----

[#test]
== Test and login to the virtual machine

Now that the virtual machine is up and running, you can see if the application behaves the same:

----
curl http://qcow-vm
----

And the results should be the "Hello Red Hat" string defined in the Containerfile.

You can also login to the virtual machine:

----
ssh lab-user@qcow-vm
----

If the ssh key is not automatically picked up, use the password defined in the JSON file at the beginning of this lab (by default `lb1506`).

Once you have logged in, you can inspect the bootc status (the password for `sudo` is `lb1506`):

----
sudo bootc status
----

The output should look similar to this:

[source,yaml]
----
apiVersion: org.containers.bootc/v1alpha1
kind: BootcHost
metadata:
  name: host
spec:
  image:
    image: summit.registry/lb1506:bootc
    transport: registry
  bootOrder: default
status:
  staged: null
  booted:
    image:
      image:
        image: summit.registry/lb1506:bootc
        transport: registry
      version: 9.20240501.0
      timestamp: null
      imageDigest: sha256:0a3daed6e31c2f2917e17ea994059e1aaee0481fe16836c118c5e1d10a87365c
    cachedUpdate: null
    incompatible: false
    pinned: false
    ostree:
      checksum: 008e3bef805f25224f591240627bea2a06ce12b25494836c2dab7d1b0a1691a8
      deploySerial: 0
  rollback: null
  rollbackQueued: false
  type: bootcHost
----

Congratulations, you are running a bootc virtual machine! From the output of `bootc status` you can clearly see the virtual machine is running the `summit.registry/lb1506:bootc` container image.

You can explore the virtual machine before moving on to the next section:

  * `systemctl status httpd` -> see the `httpd` service we have enabled in the Containerfile
  * `cat /var/www/html/index.html` -> see the index.html file we have created in the Containerfile

Before proceeding, make sure you have logged out of the virtual machine:

[source,bash]
----
logout
----

The prompt should read `[lab-user@hypervisor rh-summit-2024-lb1506]$` before continuing.
