= Deploying a bootc virtual machine with Anaconda

In this lab you will learn the basics of deploying a bootc image using Anaconda and an
all in one `iso` image.

Anaconda is the official Red Hat Enterprise Linux and it uses Kickstart as it's scripting language. Kickstart
received a new command called `ostreecontainer`.

[#build]
== Building an installation iso with the bootc container

In this lab, you will be using the CentOS Stream 9 minimal installation iso image
as it is publicly available, but rest assured that the steps are identical for a Red Hat Enterprise Linux 9.4 `iso` image
and even for Fedora 40 or newer.

The image should have been already downloaded at the setup phase at the beginning of this workshop. You can check it exists
by listing the file `/var/lib/libvirt/images/summit/rhel-boot.iso` as root:

[source,bash]
----
sudo ls -lah /var/lib/libvirt/images/summit/rhel-boot.iso
----

If it is missing, you can redownload it by calling `make iso-download`.

Next, make sure you have pushed the bootc container image to the local registry:

----
podman push summit.registry/bifrost:bootc
----

The actual generation of the custom `iso` image is out of scope for this workshop, so we are providing a convenient script to do so:

[source,bash]
----
make iso CONTAINER=summit.registry/bifrost:bootc
----

At the end of the run, you should be able to list the file `/var/lib/libvirt/images/summit/rhel-boot-custom.iso` as root:

----
sudo ls -lah /var/lib/libvirt/images/summit/rhel-boot-custom.iso
----

For reference, the script used to embed and build the custom iso can be found in `bin/embed-container` and it can
be resumed with the following steps (no need to run these commands):

  1. use `skopeo` to copy the container image to a temporary directoy on disk:

+
----
skopeo copy "docker://summit.registry/bifrost:bootc" "oci:${TEMPDIR}/container/"
----

  2. generate a Kickstart file (more details below)
  3. create the new iso using `mkksiso`

+
----
mkksiso --ks local.kickstart --add ${TEMPDIR}/container/ original.iso custom.iso
----

The Kickstart added to the iso is in `config/local.ks` and looks like this:

----
text
network --bootproto=dhcp --device=link --activate
clearpart --all --initlabel --disklabel=gpt
reqpart --add-boot
part / --grow --fstype xfs

ostreecontainer --url=/run/install/repo/container --transport=oci

firewall --disabled
services --enabled=sshd
sshkey --username lab-user "SSHKEY"
user --name="lab-user" --groups=wheel --plaintext --password=bifrost
rootpw bifrost
poweroff
----

Please note there are no rpm packages mentioned anywhere, just a `ostreecontainer` command:

  * `--url=/run/install/repo/container` -> path to the local container in the iso but it can also directly take a publicly availalbe registry
  * `--transport=oci` -> the format in which the container is available, in this case `oci`

If you wanted to deploy directly from a container registry, the `ostreecontainer` command would look like this (no need to run this command):

----
ostreecontainer --url=quay.io/myorg/myimage:mytag
----

[#run]
== Starting the installation with Anaconda in a virtual machine

In the previous section, you have created a custom installation iso. Let's see how a virtual machine booting off that image looks like. Creating
a virtual machine from scratch is out of scope for this workshop, so we have provided a script to create the virtual machine:

----
make vm-iso
----

The command above will start the installation process and you should be able to see the console of a newly created virtual machine
booting from the custom iso and automatically starting the installation process. This process is cumbersome for virtual machines, 
but it is the process most generally used for bare metal hosts. It shows how a container image can make it's way anywhere with a 
couple of simple commands and scripts. It's also important to note, everything needed is inside the custom iso created and at no
point is network access required.

For reference, if you want to manually create the virtual machine, the command looks like this (no need to run this command):

----
virt-install --connect qemu:///system \
        --name vm-iso \
        --disk "pool=summit-storage,size=50" \
        --network "network=summit-network,mac=de:ad:be:ef:01:01" \
        --location /var/lib/libvirt/images/summit/rhel-boot-custom.iso,kernel=images/pxeboot/vmlinuz,initrd=images/pxeboot/initrd.img \
        --extra-args="inst.ks=hd:LABEL=CentOS-Stream-9-BaseOS-x86_64:/local.ks console=tty0 console=ttyS0,115200n8" \
        --memory 4096 \
        --graphics none \
        --noreboot
virsh --connect qemu:///system start vm-iso
----

[#test]
== Test and login to the virtual machine

----
curl http://iso-vm
----

----
virsh --connect qemu:///system list
----

----
ssh lab-user@iso-vm
----

----
bootc status
----

----
podman pull --tls-verify=false summit.registry/bifrost:bootc
bootc --transport containers-storage summit.registry/bifrost:bootc
systemctl reboot
----
